import spam
print(dir(spam))
print(spam.plusOne("echo 'hello'",6))
r=spam.link()
print("=======")
print(r)
print(spam.getDO())
print(spam.getDI())
print(spam.getchanelVolt(0))
#print(spam.putchanelVolt(0,-10))
#print(spam.plusOne(1))